config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }

  root :to => "top#index"
  get "/post_strings/new" => "post_strings#new"
  get "/post_strings/index" => "post_strings#index"
  post 'post_strings/create' => "post_strings#create"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post_string.rb
class PostString < ApplicationRecord

  belongs_to:user
  
  validates :body, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many:post_strings
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout 'application'

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    post_strings_new_path
  end

  def after_sign_up_path_for(resource)
    post_strings_new_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
      keys: [
      :name
      ])
  end

end

app/controllers/post_strings_controller.rb
class PostStringsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  protect_from_forgery

  def index
    @post_strings = PostString.all.order(created_at: :desc).page(params[:page])
  end

  def new
    @post_string = PostString.new
    @user_id = current_user.id
  end

  def create
    post_string = PostString.new(post_string_params)
    if post_string.save
      redirect_to post_strings_index_path, notice: "投稿しました"
    else
      redirect_to post_strings_new_path, alert: "投稿できませんでした。"
    end
  end

  private def post_string_params
    params.require(:post_string).permit(:user_id, :body)
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_strings_helper.rb
module PostStringsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light p-3">
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <a class="navbar-brand" href="/">
        <div>
          <h3>SampleApp
        </div>
      </a>
      <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li>
          <%=link_to "Top", root_path %>
        </li>
        <li>
          <%=link_to "投稿一覧", post_strings_index_path %>
        </li>
        <li>
          <%=link_to "投稿フォーム", post_strings_new_path %>
        </li>
        <li>
          <%=link_to "ログアウト", destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
        <li>
          <%=link_to "Top", root_path %>
        </li>
        <li>
          <%=link_to "ログイン", new_user_session_path %>
        </li>
        <li>
          <%=link_to "新規アカウント登録", new_user_registration_path %>
        </li>
        <li>
          <%=link_to "投稿一覧", post_strings_index_path %>
        </li>
      <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ServerSideB</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div id="notice"><%= notice %></div>
    <div id="alert"><%= alert %></div>
    <main>
    <div class='container'>
      <div class='row' style = "margin-top: 50px;">
        <div class="col-12">
          <div class="text-center">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
    </main>
  </body>
</html>

app/views/post_strings/index.html.erb
      <h2>投稿一覧</h2>
      <table class="table">
        <thead>
          <tr>
            <th>投稿者</th>
            <th>内容</th>
            <th>作成日時</th>
          </tr>
        </thead>
        <tbody>
          <% @post_strings.each do |pt| %>
          <tr>
            <td>
              <%= User.find(pt.user_id).name %>
            </td>
            <td>
              <%= pt.body %>
            </td>
            <td>
              <%= pt.created_at.strftime("%Y年%m月%d日 %H時%M分") %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @post_strings %>
    </div>
  </div>
</div>

app/views/post_strings/new.html.erb
      <h2>投稿フォーム</h2>
      <div class="form-group">
      <%= form_with model:@post_string, url: post_strings_create_path, method: :create do |f| %>
        <%= f.hidden_field :user_id, value: @user_id %>
        <div>
          <%= f.text_area :body, placeholder: "文字を入力ください", autofocus: true, autocomplete: "body",  rows: "6" %>
        </div>
        <div>
          <%= f.submit "投稿" %>
        </div>
      <% end %>
      </div>

app/views/top/index.html.erb
      <h2>Top</h2>
      <p>各種リンクから機能を操作ください<p>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "新規アカウント登録", new_registration_path(resource_name) %><br />
<% end %>